import { Timestamp } from 'firebase/firestore';

export interface UserSettings {
    email: string;
    displayName: string;
    baseCurrency: string;
    manualExchangeRates: {
        [key: string]: number;
    };
    categories: string[];
    financialGoal: number;
    totalInvestmentSpent?: number; // 累計已執行金額
    aiStrategies?: AIStrategy[];
    aiTools?: AITool[];
    createdAt: Timestamp;
    lastSyncAt: Timestamp;
}

export interface AIStrategy {
    id: string;
    name: string;
    promptTemplate: string;
    description: string;
    iconType: string;
}

export interface AITool {
    id: string;
    name: string;
    url: string;
}

export interface MonthlyConfigItem {
    category: string;
    ticker: string;
    amount: number;
    currency: string;
}

export interface MonthlyConfig {
    uid: string;
    configName: string;
    items: MonthlyConfigItem[];
    idleFundsByCurrency?: {
        [currency: string]: {
            amount: number;
            startMonth: string;
            endMonth: string;
        }
    };
    rationale?: string;
    investmentHorizon?: string;
    riskTolerance?: string;
    investmentPsychology?: string;
    manualIdleFunds?: string | number;
    investmentNotes?: string;
    updatedAt: Timestamp;
}

export interface SnapshotAllocation {
    ticker: string;
    amount: number;
    currency: string;
    category: string;
}

export interface Snapshot {
    id?: string;
    uid: string;
    yearMonth: string; // YYYY-MM
    totalInvestedInBase: number; // 本月投入總額 (換算至基準幣別)
    allocationSnapshot: SnapshotAllocation[]; // 本月分配明細
    isAutoGenerated: boolean;
    createdAt: Timestamp;
}

export interface StockCache {
    price: number;
    currency: string;
    lastFetchAt: Timestamp;
}
