import { Timestamp } from 'firebase/firestore';

export interface UserSettings {
    email: string;
    displayName: string;
    baseCurrency: string;
    manualExchangeRates: {
        [key: string]: number;
    };
    categories: string[];
    financialGoal: number;
    aiStrategies?: AIStrategy[];
    aiTools?: AITool[];
    createdAt: Timestamp;
    lastSyncAt: Timestamp;
}

export interface AIStrategy {
    id: string;
    name: string;
    promptTemplate: string;
    description: string;
    iconType: string;
}

export interface AITool {
    id: string;
    name: string;
    url: string;
}

export interface Holding {
    id?: string;
    uid: string;
    ticker: string;
    name: string;
    category: string;
    shares: number;
    avgCost: number;
    currency: string;
    currentPrice: number;
    updatedAt?: Timestamp;
}

export interface MonthlyConfigItem {
    category: string;
    ticker: string;
    amount: number;
    currency: string;
}

export interface MonthlyConfig {
    uid: string;
    configName: string;
    items: MonthlyConfigItem[];
    idleFunds?: number;
    rationale?: string;
    updatedAt: Timestamp;
}

export interface SnapshotHolding {
    ticker: string;
    shares: number;
    price: number;
    subtotal: number;
}

export interface SnapshotAllocation {
    ticker: string;
    amount: number;
    currency: string;
}

export interface Snapshot {
    id?: string;
    uid: string;
    yearMonth: string; // YYYY-MM
    totalValueInBase: number;
    holdingsSnapshot: SnapshotHolding[];
    allocationSnapshot: SnapshotAllocation[];
    isAutoGenerated: boolean;
    createdAt: Timestamp;
}

export interface StockCache {
    price: number;
    currency: string;
    lastFetchAt: Timestamp;
}
